data_guest: "../../data/epsilon_5k_hetero_guest.csv"
data_host: "../../data/epsilon_5k_hetero_host.csv"
idx: "id"
label_name: "y"
penalty: "L2"
max_iter: 30
alpha: 0.0001
learning_rate: 0.15
optimizer: "rmsprop"
batch_size: 800
early_stop: "diff"
init_method: "zeros"