data_guest: "../../data/epsilon_5k_hetero_guest.csv"
data_host: "../../data/epsilon_5k_hetero_host.csv"
idx: "id"
label_name: "y"
penalty: "L2"
max_iter: 15
alpha: 0.001
learning_rate: 0.15
optimizer: "rmsprop"
batch_size: 3200
early_stop: "diff"