data_guest: "/home/mingchao/python/examples/data/default_credit_hetero_guest.csv"
data_host: "/home/mingchao/python/examples/data/default_credit_hetero_host.csv"
idx: "id"
label_name: "y"
penalty: "L2"
max_iter: 100
alpha: 0.01
learning_rate: 0.15
