data_guest: "/home/mingchao/python/examples/data/vehicle_scale_hetero_guest.csv"
data_host: "/home/mingchao/python/examples/data/vehicle_scale_hetero_host.csv"
idx: "id"
label_name: "y"
penalty: "L2"
max_iter: 30
alpha: 0.01
learning_rate: 0.15
optimizer: "rmsporp"
