data_guest: "/home/cwj/FATE/standalone-fate-master-1.4.5/examples/data/breast_hetero_guest.csv"
data_host: "/home/cwj/FATE/standalone-fate-master-1.4.5/examples/data/breast_hetero_host.csv"
idx: "id"
label_name: "y"
