data_guest: "../../data/breast_homo_guest.csv"
data_host: "../../data/breast_homo_host.csv"
data_test: "../../data/breast_homo_test.csv"
idx: "id"
label_name: "y"
penalty: "L2"
max_iter: 3
alpha: 0.01
learning_rate: 0.15
optimizer: "rmsprop"
