data_guest: "/home/mingchao/python/examples/data/epsilon_5k_homo_guest.csv"
data_host: "/home/mingchao/python/examples/data/epsilon_5k_homo_host.csv"
data_test: "/home/mingchao/python/examples/data/epsilon_5k_homo_guest.csv"
idx: "id"
label_name: "y"
penalty: "L2"
max_iter: 3
alpha: 0.001
learning_rate: 0.15
optimizer: "rmsprop"
