data_guest: "../../data/give_credit_homo_guest.csv"
data_host: "../../data/give_credit_homo_host.csv"
data_test: "../../data/give_credit_homo_test.csv"
idx: "id"
label_name: "y"
penalty: "L2"
max_iter: 15
alpha: 1
learning_rate: 0.15
optimizer: "rmsprop"
