epoch: 1000
lr: 0.05
batch_size: -1
optimizer: Adam
encode_label: false
layers:
  - name: Dense
    params: { units: 5, input_shape: [ 30 ], activation: relu }
  - name: Dense
    params: { units: 1, activation: softmax }
dataset: breast
loss: binary_crossentropy
is_multy: false
metrics: [ "accuracy" ]