data_guest: "/data/projects/fate/examples/data/vehicle_scale_homo_guest.csv"
data_host: "/data/projects/fate/examples/data/vehicle_scale_homo_host.csv"
data_test: "/data/projects/fate/examples/data/vehicle_scale_homo_test.csv"
idx: "id"
label_name: "y"
