# ssh tunnel forwarder, request remote services through local port
# uncomment flowing and modify fields according to there comments if at least one
# FATE party is unreachable from where you running testsuite.
#ssh_tunnel:
#  - ssh_address:  172.0.0.1:22 # format: ip:port, ssh address to login,
#    ssh_username: app  # ssh username
#    ssh_password: ??  # ssh password, optional, if `ssh_priv_key` provided
#    ssh_priv_key: "~/.ssh/id_rsa"  # ssh priv key path, optional, if `ssh_password` provided
#    services:  # flow services to bind
#      - address: 127.0.0.1:9380
#        parties: [9999]

# flow services in local, could be comments out
# if all `FATE` server are unreachable from  where you running testsuite.
local_services:
  - address: 127.0.0.1:9380
    parties: [9999, 10000]

# assignment parties
parties:
  guest:
    - 10000
  host:
    - 9999
    - 10000
  arbiter:
    - 9999

# work mode, accept 0 or 1, dependents on `FATE` deployed mode.
work_mode: 0

# base dir of data file path in data conf
# we need these path to correct the data file path for testsuite.
# eg. for flowing data config:
#  {
#    "file": "examples/data/breast_hetero_guest.csv",
#    "head": 1,
#    "partition": 16,
#    "work_mode": 0,
#    "table_name": "breast_hetero_guest",
#    "namespace": "experiment",
#  }
# we need to reinterpret as `$data_base_dir/examples/data/breast_hetero_guest.csv`
# dir could be relative to these config.
data_base_dir: ../../../

