data_guest: "examples/data/give_credit_hetero_guest.csv"
data_host: "examples/data/give_credit_hetero_host.csv"
idx: "id"
label_name: "y"
learning_rate: 0.15
tol: 0.01
loss: "binary_crossentropy"
batch_size: 3000
metrics: ["AUC"]
epochs: 60
bottom_layer_units: 2
interactive_layer_units: 1
top_layer_units: 1
guest_table_name: "give_credit_hetero_guest"
host_table_name: "give_credit_hetero_host"
top_act: "sigmoid"
